### PR TITLE
switch to protocol agnostic links

### PR DESCRIPTION
**Pull request by erfanio**

### CODE REVIEW

**Comment by erfanio** [comment]
please check if it compiles
I don't have ruby on my laptop :P

**Comment by josh-** [comment]
Doesn't compute for me until I `bundle update` 😆 but then all good ✅

**Review by josh- — CHANGES_REQUESTED** [review]
Shouldn't need to change the `_config.yml`, see the corresponding PR here:  https://github.com/unihackhq/unihackhq.github.io/pull/19

**Comment by erfanio** [comment]
@josh- so we assume `/press/` is gonna be the root?

**Comment by erfanio** [comment]
I just changed the url in `_config.yaml` since we don't have a use for `site.url` otherwise

**Review by josh- — APPROVED** [review]
LGTM 👍

**Pull request merged**
